config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources  :pictures, only: [:new, :edit]
  get "users/new"
  root 'static_pages#home'

  match '/signup', to: 'users#new', via: 'get'
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  match '/help',to: 'static_pages#help', via: 'get'
  match '/about',to: 'static_pages#about', via: 'get'
  match '/contact',to: 'static_pages#contact', via: 'get'
  match '/edit', to: 'users#edit', via: 'get'

  

end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :picture, PictureUploader
  has_many :microposts, dependent: :destroy
  has_many :relationships, foreign_key: "follower_id", dependent: :destroy
  has_many :followed_users, through: :relationships, source: :followed
  has_many :reverse_relationships, foreign_key: "followed_id",
           class_name:  "Relationship",
           dependent:   :destroy
  has_many :followers, through: :reverse_relationships, source: :follower
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50, minimum: 8}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: { case_sensitive: false }
  has_secure_password
  VALID_PASSWORD_REGEX = /\A[A-Z]+[[a-zA-Z]+\d+]+[A-Z]+\z/
  validates :password, length: { minimum: 6 }

  before_create :create_remember_token

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s) # SHA1 faster than bcrypt
  end

  def feed
    Micropost.from_users_followed_by(self)
  end

  def following?(other_user)
    relationships.find_by(followed_id: other_user.id)
  end

  def follow!(other_user)
    relationships.create!(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    relationships.find_by(followed_id: other_user.id).destroy
  end

  def save_and_process_picture(options = {})
    if options[:now]
      puts "He entrado a guardar desde el worker con el #{self.name} y #{self.id}"
      self.remote_picture_url = picture.direct_fog_url(:with_path => true)
      image = MiniMagick::Image.open(self.picture.current_path)
      image.resize "50x50"
      image.write "#{self.picture.current_path}"
      puts "Esta es la url remota #{self.remote_picture_url}"
      puts "Imagen #{self.picture}"
      #self.password = '123456789'
      #self.password_confirmation = '123456789'
      puts "Contraseña : #{self.password}"
      puts "Se intenta guardar"
      if save
        puts "Se ha guardado en S3"
      else
        puts "No se ha guardado"
      end
    else
      puts "He encolado desde el create"
      puts "He encolado desde el create con contraseña #{self.password}"
      Resque.enqueue(PictureProcessor, self.id, self.key, self.password)
      true
      puts "He salido de la cola desde el create"
    end
  end

  private # hidden from everyone except the User model
  def create_remember_token # 2
    self.remember_token = User.encrypt(User.new_remember_token) # self = the object being created
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  def new
    @user = params[:key] ? User.new(picture_params): User.new
  end

  def index
    @users = User.paginate(page: params[:page])
  end


  def create
    @user = User.new(user_params) # Not the final implementation!
    #if @user.save
    #  Resque.enqueue(PictureProcessor, @user.id, @user.key)
    #  sign_in @user
    #  flash[:success] = "Welcome to the Sample App!"
    #  redirect_to @user
    #else
    #  render 'new'
    #end

      if @user.save
        @user.save_and_process_picture
        puts "He guardado"
        sleep 5
        sign_in @user
        flash[:success] = "Welcome to the Sample App!"
        redirect_to @user
      else
        puts "No he podido guardar"
        render 'new'
      end

  end

  def edit
    @user = User.find(params[:id])
    if (params[:key])
      @user.key = params[:key]
    end
  end

  def update
    if @user.update_attributes(user_params)
      @user.save_and_process_picture
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.followed_users.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private # internal to Users controller
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,:picture, :key)
  end
  # Before filters
  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end

  def picture_params # add this private method
    params.permit(:key)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.build(followed_id: @user.id), remote: true) do |f| %>
    <div><%= f.hidden_field :followed_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form">
      <% if current_user.following?(@user) %>
          <%= render 'unfollow' %>
      <% else %>
          <%= render 'follow' %>
      <% end %>
    </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <div class="gravatar">
    <% if user.picture.present? %>
        <a href="<%= user.picture_url %>"><%= image_tag(user.picture_url, :width => 52) %></a>
    <% else %>
        <%= image_tag("default.png", :width => 52) %>
    <% end %>
  </div>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
      | <%= link_to "delete", user, method: :delete,
                    data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, :html => {:multipart => true}  do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label :name %>
        <%= f.text_field :name %>

        <%= f.label :email %>
        <%= f.text_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.label :password_confirmation, "Confirm Password" %>
        <%= f.password_field :password_confirmation %>

        <% unless @user.has_picture_upload? %>

            <%= link_to "Upload Picture", edit_picture_path(:id=>@user.id) %>

        <% else %>
            <%= "File \"#{File.basename(@user.key)}\" has been uploaded  to S3." %>

            <%= link_to "Upload Picture", edit_picture_path(:id=>@user.id) %>

        <% end %>

        <%= f.hidden_field :key %>

        <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <!--<%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>-->
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
      <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for @user, :html => {:multipart => true}  do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %>

        <% unless @user.has_picture_upload? %> <!-- this is the code to be added -->
            <%= link_to "Upload Picture", new_picture_path %>
        <% else %>
            <%= "File \"#{File.basename(@user.key)}\" has been uploaded  to S3." %>
            <%= link_to "Upload Picture", new_picture_path %>
        <% end %>

        <%= f.hidden_field :key %>

        <!--<%= f.label :picture %>
        <%= f.file_field :picture %>-->
        <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row"> <!-- Bootstrap classes: row, span -->
  <aside class="span4">
    <section>
      <h1>
        <div class="gravatar">
        <% if @user.picture.present? %>
            <a href="<%= @user.picture_url %>"> <%= image_tag(@user.picture_url, :width => 52) %></a>
        <% else %>
            <%= image_tag("default.png", :width => 52) %>
        <% end %>
        </div>

        <%= @user.name %>
      </h1>
    </section>
    <section>
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="span8">
    <%= render 'follow_form' if signed_in? %>
    <% if @user.microposts.any? %>
        <h3>Microposts (<%= @user.microposts.count %>)</h3>
        <ol class="microposts">
          <%= render @microposts %>
        </ol>
        <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="span4">
    <section>
      <div class="gravatar">
      <% if @user.picture.present? %>
          <a href="<%= @user.picture_url %>"><%= image_tag(@user.picture_url, :width => 52) %></a>
      <% else %>
          <%= image_tag("default.png", :width => 52) %>
      <% end %>
      </div>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section>
      <%= render 'shared/stats' %>
      <% if @users.any? %>
          <div class="user_avatars">
            <% @users.each do |user| %>
                <div class="gravatar">
                <% if user.picture.present? %>
                    <%= image_tag(user.picture_url, :width => 30) %>
                <% else %>
                    <%= image_tag("default.png", :width => 30) %>
                <% end %>
                </div>
            <% end %>
          </div>
      <% end %>
    </section>
  </aside>
  <div class="span8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
        <ul class="users">
          <%= render @users %>
        </ul>
        <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/upload.html.erb
<%= direct_upload_form_for @uploader do |f| %>
    <%= f.file_field :picture %>
    <%= f.submit "Upload picture" %>
<% end %>